### ISSUE TITLE
rez-bind python get the error

### ISSUE THREAD

**Issue by mxc123** [AcademySoftwareFoundation/rez#1082]
rez-bind --quickstart
Binding platform into C:\Users\mcc\packages...
10:18:41 WARNING  Skipping installation: Package variant already exists: c:\users\mcc\packages\platform\windows\package.py[]
Binding arch into C:\Users\mcc\packages...
10:18:41 WARNING  Skipping installation: Package variant already exists: c:\users\mcc\packages\arch\AMD64\package.py[]
Binding os into C:\Users\mcc\packages...
10:18:41 WARNING  Skipping installation: Package variant already exists: c:\users\mcc\packages\os\windows-10.0.17763\package.py[]
Binding python into C:\Users\mcc\packages...
命令语法不正确。
Traceback (most recent call last):
  File "D:\Program Files\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Program Files\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Program Files\rez\Scripts\rez\rez-bind.exe\__main__.py", line 7, in <module>
  File "d:\program files\rez\lib\site-packages\rez\cli\_entry_points.py", line 95, in run_rez_bind
    return run("bind")
  File "d:\program files\rez\lib\site-packages\rez\cli\_main.py", line 184, in run
    returncode = run_cmd()
  File "d:\program files\rez\lib\site-packages\rez\cli\_main.py", line 176, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "d:\program files\rez\lib\site-packages\rez\cli\bind.py", line 77, in command
    quiet=True)
  File "d:\program files\rez\lib\site-packages\rez\package_bind.py", line 112, in bind_package
    quiet=quiet)
  File "d:\program files\rez\lib\site-packages\rez\package_bind.py", line 175, in _bind_package
    parser=bind_parser)
  File "d:\program files\rez\lib\site-packages\rez\bind\python.py", line 86, in bind
    pkg.post_commands = post_commands
  File "D:\Program Files\python27\Lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "d:\program files\rez\lib\site-packages\rez\package_maker.py", line 233, in make_package
    make_root(variant_, root)
  File "d:\program files\rez\lib\site-packages\rez\bind\python.py", line 70, in make_root
    platform_.symlink(exepath, link)
  File "d:\program files\rez\lib\site-packages\rez\utils\platform_.py", line 510, in symlink
    subprocess.check_output("mklink %s %s" % (link_name, source), shell=True)
  File "D:\Program Files\python27\Lib\subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'mklink c:\users\mcc\packages\python\2.7.12\platform-windows\arch-AMD64\os-windows-10.0.17763\bin\python d:\program files\python27\python.exe' returned non-zero exit status 1

E:\rez_packages\example_packages\hello_world>rez-bind python
searching d:\program files\rez\lib\site-packages\rez\bind...
creating package 'python' in C:\Users\mcc\packages...
10:23:54 WARNING  Skipping installation: Package variant already exists: c:\users\mcc\packages\python\2.7.12\package.py[0]

**Comment by ZhongLingXiao** [comment]
`subprocess.check_output("mklink %s %s" % (link_name, source), shell=True)`
in this line should change to:
`subprocess.check_output("mklink \"%s\" \"%s\" " % (link_name, source), shell=True)`

because correct syntax should go like this:
`mklink 'path1' 'path2'`
