### ISSUE TITLE
Install fails on osx with python-3.10.5

### ISSUE THREAD

**Issue by hughetop** [AcademySoftwareFoundation/rez#1340]
Attempting to install rez on osx with python3 fails during the `install_rez_from_source` because no python executable can be found.

**Environment**
* OSX 12.0
* Rez version 2.111.2
* Rez python version 3.10.5

**To Reproduce**
1. download rez-master.zip on osx and extract
2. open a terminal and navigate to the directory
3. `python3 ./install.py -v <dest_dir>`

**Expected behavior**
It should install rez to the specified destination directory

**Actual behavior**
An error occurs:
```
Traceback (most recent call last):
  File "/Volumes/server/rez/config/rez_src-2.111.2/./install.py", line 311, in <module>
    install(dest_dir, print_welcome=True)
  File "/Volumes/server/rez/config/rez_src-2.111.2/./install.py", line 156, in install
    install_rez_from_source(dest_dir)
  File "/Volumes/server/rez/config/rez_src-2.111.2/./install.py", line 223, in install_rez_from_source
    run_command([py_executable, "-m", "pip", "install", "."])
  File "/Volumes/server/rez/config/rez_src-2.111.2/./install.py", line 77, in run_command
    print("running in %s: %s" % (cwd, " ".join(args)))
TypeError: sequence item 0: expected str instance, NoneType found
```
Stepping through the install process, it seems in rez.utils.which, the `_access_check` fails because `os.access` returns False. I'm not sure why, the file is executable and the permissions look like:
`-rwx------  1 hughetop  staff   149K Jun 27 11:42 python`
Because of this, no python executable is passed to `run_command` and it fails.

Edit: I misremembered the permissions flags, it seems the python created in the venv is only executable by the current user. I'm not sure how that happened, it may be an org issue for me.

**Comment by hughetop** [comment]
I just tried with python-3.9.13 and it was the same thing, so I wonder if the OS is the problem...
