### ISSUE TITLE
ImportError: No module named rez.cli._entry_points

### ISSUE THREAD

**Issue by slvfx** [AcademySoftwareFoundation/rez#1367]
Describe the bug here.

**Environment**
* OS (Windows 7)
* Rez version (2.111.3)
* Rez python version (the command to get this fails)
* Python version (2.7.18)

**To Reproduce**
The first issue is that it fails to install:
```
./install.py -v C:/Rez
c:\rez\scripts\python.exe: No module named pip
```
Looking in C:/Rez/Lib/site-packages I noticed it was empty. So I tried copying over the default packages in site-packages from my Python 2.7.18 installation (including pip).

That worked! Or did it:
```
SUCCESS!
Rez executable installed to: C:\Rez\Scripts\rez\rez
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Rez\Scripts\rez\rez.exe\__main__.py", line 4, in <module>
ImportError: No module named rez.cli._entry_points

To activate Rez, add the following path to $PATH:
C:\Rez\Scripts\rez
```
Indeed, every rez command I try to run has that error:
```
ImportError: No module named rez.cli._entry_points
```
Is my Windows and/or Python too old?

**Comment by maxnbk** [comment]
Is the behavior any different if you run it from python rather than as a CLI script?
i.e. `python install.py [...]`

**Comment by slvfx** [comment]
No, exactly the same. That's with using Python 2.7.18.

**Comment by JeanChristopheMorinPerso** [comment]
Can you provide the full clog when you run the `install.py` script please? Also please run the install with `<path to python.exe> install.py <the other ARGS>` so that we can be sure which python interpreter is being used.

Also, as a side note, it's generally a pretty bad idea to copy/paste/move files from one site-packages to another.

**Comment by slvfx** [comment]
Totally agree on copy/pasting from site-packages- I'd prefer the installer do that.

Where would the full log be? This is what I see in a Windows command prompt for the first failure:
```
C:\Users\slvfx\src\rez-2.111.3>C:\Python27\python.exe install.py -v C:\Rez
installing rez to C:\Rez...
running in C:\Users\slvfx\src\rez-2.111.3: c:\rez\scripts\python.exe -m pip install .
c:\rez\scripts\python.exe: No module named pip
Traceback (most recent call last):
  File "install.py", line 311, in <module>
    install(dest_dir, print_welcome=True)
  File "install.py", line 156, in install
    install_rez_from_source(dest_dir)
  File "install.py", line 223, in install_rez_from_source
    run_command([py_executable, "-m", "pip", "install", "."])
  File "install.py", line 78, in run_command
    return subprocess.check_output(args, cwd=source_path)
  File "C:\Python27\lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['c:\\rez\\scripts\\python.exe', '-m', 'pip', 'install', '.']' returned non-zero exit status 1
```
Thanks for taking a look.

**Comment by JeanChristopheMorinPerso** [comment]
That's the full log, thanks.

Running the `install.py` file creates a virtualenv at the given location (in your case `C:\rez`) and then runs `pip install .` and then some other steps that are irrelevant to this issue.

`virtualenv` is supposed to install pip automatically for you (inside the virtualenv). So something is wrong here because we can see it's not there. Or is it and Windows is just lying to us?

I have a couple of questions:

1. How did you install python on that machine?
2. Is pip installed in this python installation (somewhere in `C:\Python27`)?
3. What the content of `C:\rez`? Does it look like a virtualenv? (Is there activation scripts in the `scripts` directory?)

**Comment by slvfx** [comment]
1. I installed it using the Windows msi installer from https://www.python.org/downloads/release/python-2718/
2. Yes, it's under C:\Python27\Lib\site-packages\pip (that's where I copied it and the other packages from, when the rez installer didn't copy them)
3. Yes, I see a bunch of files there with "activation" in the name:
```
activate
activate.bat
activate.ps1
activate_this.py
deactivate.bat
python.exe
pythonw.exe
```
Could it be a Windows 7 thing?
