### ISSUE TITLE
Error launching detached Powershell through ResolvedContext.execute_shell

### ISSUE THREAD

**Issue by nikshankarnoble** [AcademySoftwareFoundation/rez#1406]
I'm receiving an error when attempting to launched a detached shell with Powershell (5.0 and 7.0+) through the `ResolvedContext.execute_shell` method.

```
Traceback (most recent call last):
  File "C:/Users/n.shankar-noble.mull/AppData/Roaming/JetBrains/PyCharmCE2020.3/scratches/scratch_17.py", line 12, in <module>
    block=True,
  File "C:\opt\rez\Lib\site-packages\rez\resolved_context.py", line 1045, in _check
    return fn(self, *nargs, **kwargs)
  File "C:\opt\rez\Lib\site-packages\rez\resolved_context.py", line 1460, in execute_shell
    **Popen_args)
  File "C:\opt\rez\Lib\site-packages\rezplugins\shell\_utils\powershell_base.py", line 223, in spawn_shell
    p = Popen(cmd, env=env, **Popen_args)
  File "C:\opt\rez\Lib\site-packages\rez\utils\execution.py", line 91, in __init__
    super(Popen, self).__init__(args, **kwargs)
  File "C:\Python374\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python374\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Printing the `cmd` executed by the shell plugin (in `PowershellBase`) it doesn't seem to be running a valid Start-Process command:
```
['START', '-NoExit', 'c:\\program files\\powershell\\7\\pwsh.exe', '-NoLogo', '-File', 'C:\\Users\\NSHANK~1.MUL\\AppData\\Local\\Temp\\rez_context_7_3vs3yk\\rez-shell.ps1']
```
The -NoExit flag appears to be in the wrong place and believe the list of pwsh.exe arguments need to be passed as a string list through the -ArgumentList flag of Start-Process.

Running a non-detached shell with Powershell is working without issue. 

**Environment**
* OS: Windows 10
* Rez version: 2.111.3
* Rez python version: Python 3.7.4

**To Reproduce**
Execute the following Python code with `rez-python`:
```
import os
from rez.resolved_context import ResolvedContext
context = ResolvedContext(['python'])
returncode, stdout, stderr = context.execute_shell(
    parent_environ=os.environ.copy(),
    shell="pwsh",
    detached=True,
    block=True,
)
```

**Expected behavior**
Expected behaviour is that a new Powershell window would be opened in the ResolvedContext.

**Actual behavior**
The error listed above, with no shell launched.

**Comment by instinct-vfx** [comment]
Thanks a lot for the report!  For my own reference after a quick look spawning a interactive shell fails with just running start, so the issue is likely already in the Popen args.

**Comment by nikshankarnoble** [comment]
Happy New Year all! I had a little look into this over the new year's break and found a couple of issues with how it's launching the detached Powershell process. 

If we print the `cmd` argument getting passed down into the Popen in `rezplugins/shell/_utils/powershell_base.py`:

```
> rez env ipython --detached --shell pwsh 
['START', '-NoExit', 'c:\\program files\\powershell\\7\\pwsh.exe', '-NoLogo', '-File', 'C:\\Users\\NSHANK~1.MUL\\AppData\\Local\\Temp\\rez_context_pa5gbw4p\\rez-shell.ps1']
```

The first issue is that the `-NoExit` argument to `pwsh` is being called as the executable for START, rather than as an argument to pwsh.exe.

The second issue is that the default install location for Powershell 7 - `C:/Program Files/Powershell/7/` - has a space in it's name, which the START command doesn't like by default, it tries to launch `C:/Program` as the executable which then gives the FileNotFoundError.

I've tried a few ways of escaping the space in a way that is compatible with the START command, and with the CreateProcess() call that the Popen makes (that works currently). Based on the following thread I tried wrapping the space in quotes, and wrapping the whole executable with a dummy title string, but neither worked for me. I'm hoping someone a little better versed in the Windows world might have a little more luck than myself.
https://superuser.com/questions/239565/can-i-use-the-start-command-with-spaces-in-the-path

A very hacky "solution" that is working for me is to use the short name of the executable (with it on the PATH), `pwsh.exe`, and setting `shell=True` on the Popen to run through cmd.exe rather than CreateProcess(), so the existing code

```
cmd += [self.executable]
cmd += ["NoLogo"]
...
if shell_command is None:
    cmd.insert(1, "-NoExit")
```
becomes
```
if cmd and cmd[0] == "START":
    cmd += ["pwsh.exe"]
    Popen_args["shell"] = True
else:
    cmd += [self.executable]

cmd += ["NoLogo"]
if shell_command is None:
    cmd.append("-NoExit")
...
```

I'm not suggesting this as a solution or anything, just wanted to record it as a potential hacky workaround! :)

Will keep looking into a good way to escape the Powershell path with START, but if anyone else has time to look at it as well that would be very much appreciated!

Best,
Nikhil

**Comment by FhyTan** [comment]
Hi, I encountered the same issue when using ResolvedContext.execute_shell on Windows. It seems that the subprocess call fails because it cannot find the START command when shell=True is not passed to the underlying Popen call.

### Environment：
- OS: Windows 10
- Rez Version: 3.3.0
- Python Version: 3.12.10

### Debug Information
I performed a debug trace and found that the command being executed is:
```python
subprocess.Popen([
    "START",
    "c:\\windows\\system32\\windowspowershell\\v1.0\\powershell.exe",
    "-NoLogo",
    "-File",
    "C:\\Users\\tan\\AppData\\Local\\Temp\\rez_context_vut5gtro\\rez-shell.ps1",
])
```
The error raised is:
FileNotFoundError: [WinError 2] The system cannot find the file specified

In Windows, START is a built-in command of the shell (cmd.exe), not a standalone executable. Therefore, subprocess.Popen cannot find it unless shell=True is specified.

However, in ResolvedContext.execute_shell, the shell parameter is repurposed to specify which shell to use (e.g., cmd, powershell, bash), making it impossible to pass the standard subprocess shell=True argument through to the internal call.
