### ISSUE TITLE
rez-env Fails Due to Build Metadata in Version String

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [AcademySoftwareFoundation/rez#1447]
I have a package that is using the following as its version string: `3.3.0+b75c1cb`
This does follow the semantic versioning conventions, as you can check [here](https://regex101.com/r/AdEeah/1)

However, it causes the following exception:

```
Traceback (most recent call last):
  File "c:\opt\rez\lib\site-packages\rez\vendor\version\version.py", line 867, in __init__
    parser = _VersionRangeParser(range_str, make_token,
  File "c:\opt\rez\lib\site-packages\rez\vendor\version\version.py", line 669, in __init__
    raise ParseException("Syntax error in version range '%s'" % part)
rez.vendor.version.util.ParseException: Syntax error in version range '3.3.0+b75c1cb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\opt\rez\Scripts\rez\rez-env.exe\__main__.py", line 7, in <module>
  File "c:\opt\rez\lib\site-packages\rez\cli\_entry_points.py", line 148, in run_rez_env
    return run("env")
  File "c:\opt\rez\lib\site-packages\rez\cli\_main.py", line 191, in run
    returncode = run_cmd()
  File "c:\opt\rez\lib\site-packages\rez\cli\_main.py", line 183, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "c:\opt\rez\lib\site-packages\rez\cli\env.py", line 203, in command
    context = ResolvedContext(
  File "c:\opt\rez\lib\site-packages\rez\resolved_context.py", line 220, in __init__
    req = PackageRequest(req)
  File "c:\opt\rez\lib\site-packages\rez\utils\formatting.py", line 74, in __init__
    super(PackageRequest, self).__init__(s)
  File "c:\opt\rez\lib\site-packages\rez\vendor\version\requirement.py", line 156, in __init__
    self.range_ = VersionRange(
  File "c:\opt\rez\lib\site-packages\rez\vendor\version\version.py", line 871, in __init__
    raise VersionError("Syntax error in version range '%s': %s"
rez.vendor.version.util.VersionError: Syntax error in version range '3.3.0+b75c1cb': Syntax error in version range '3.3.0+b75c1cb'
```

**Environment**
* OS: windows
* Rez version (2.112.0
* Rez python version: 3.9.13

**To Reproduce**
1. Request a package including semantic versioning build metadata. The package does not have to exist for the exception to be raised. e.g `rez-env blah-0.0.1+badf00d`
2. Observe the exception

**Expected behavior**
Rez should locate the package

**Actual behavior**
The above exception

I'm guessing that the presence of a `+` is being treated as a range, but should that only be the case when the character to the right is a space (`rez-env blah-1+ bob-0.2.0`) or a `<`, `>' symbol (`rez-env blah-1+<2 bob-0.2.0`).

So the fundamental question is, should rez conver this use case?

**Comment by bpabel** [comment]
I think this is a use case that should be supported since it's a feature of a popular and widely used versioning scheme.

There are a couple issues that may complicate supporting this:

- Versions and Package Orderers aren't currently designed to be plugin-able. 
- Version parsing isn't configurable, it is global across all packages and package-families.
- Orderers are configurable, but not in a way that's scalable IMO, since it's configured in the global configuration, and not by package-family (indeed, there are no package-family configuration files at the moment).
