### ISSUE TITLE
Unexpected behaviour with variants

### ISSUE THREAD

**Issue by dominiquekwiek** [AcademySoftwareFoundation/rez#1458]
I wanted clarification on transitive package inclusion when using variants.  I have the following use case:

![Blank diagram](https://user-images.githubusercontent.com/28793110/224383547-0abefb63-046d-4299-8893-757d43466dee.png)

Package B package.py is:

```python
name = "package_b"

version = "0.1.0"

requires = ["package_a"]

variants = [
   ["package_c"],
   ["package_d"]
]

...

```

With the following rez command:

`rez-env package_b`

I would expect `package_b` to bring in `package_a` which by requirement would include `package_a` and the `package_a` variant of `package_b` would be resolved.

Instead, **both** variants of `package_b` are being resolved such that:

```
rez-env package_b
...
resolved packages:
package_a-0.1.0  /dev/packages/package_a/0.1.0            (local)
package_b-0.1.0  /dev/packages/package_b/0.1.0/package_d  (local)
package_c-0.1.0  /dev/packages/package_c/0.1.0            (local)
package_d-0.1.0  /dev/packages/package_d/0.1.0            (local)
```

Am I misunderstanding how this should work?

**Comment by maxnbk** [comment]
This is effectively a demonstration of the mutual exclusivity issue.
package_b expresses that it is valid to resolve with package_c, and d via variants. Therefore, solving with either is valid.
package_b also expresses a requirement that it must solve with package_a. package_a in turn requires package_c, so the solve must have c. But nothing expresses that package_b's variant is invalid if package_d is selected when c is also present. All packages can co-exist, so effectively you are subject to the specific determinism of the solver.

The behavior you're looking for is expressed more like this (though is only valid with hashed variants because "!" in filepaths is generally a bad time for FS/OS/shell reasons):

```
name = "package_b"

version = "0.1.0"

requires = ["package_a"]

variants = [
   ["package_c", "!package_d"],
   ["package_d", "!package_c"]
]
```

Addressing this issue in a broader scope is an interesting discussion, but I wanted to post this explanation to give food for thought for the moment.

**Comment by maxnbk** [comment]
(I should add that if either package_a or package_c expressed a negation on package_d in their requirements, you would also get the expected result.)

**Comment by dominiquekwiek** [comment]
This seems to fail on making the `["package_d", "!package_c"]` variant as it's running:

```
rez-env package_a package_d '!package_c
```

Which results in:

```
Traceback (most recent call last):
  File "/apps/rez/bin/rez/rez-env", line 8, in <module>
    sys.exit(run_rez_env())
  File "/apps/rez/lib/python3.6/site-packages/rez/cli/_entry_points.py", line 144, in run_rez_env
    return run("env")
  File "/apps/rez/lib/python3.6/site-packages/rez/cli/_main.py", line 184, in run
    returncode = run_cmd()
  File "/apps/rez/lib/python3.6/site-packages/rez/cli/_main.py", line 176, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "/apps/rez/lib/python3.6/site-packages/rez/cli/env.py", line 212, in command
    package_caching=(not opts.no_pkg_cache)
  File "/apps/rez/lib/python3.6/site-packages/rez/resolved_context.py", line 308, in __init__
    resolver.solve()
  File "/apps/rez/lib/python3.6/site-packages/rez/utils/memcached.py", line 267, in wrapper
    return func(*nargs, **kwargs)
  File "/apps/rez/lib/python3.6/site-packages/rez/resolver.py", line 120, in solve
    solver_dict = self._solver_to_dict(solver)
  File "/apps/rez/lib/python3.6/site-packages/rez/resolver.py", line 432, in _solver_to_dict
    graph_ = solver.get_graph()
  File "/apps/rez/lib/python3.6/site-packages/rez/solver.py", line 2258, in get_graph
    return self.get_fail_graph()
  File "/apps/rez/lib/python3.6/site-packages/rez/solver.py", line 2270, in get_fail_graph
    return phase.get_graph()
  File "/apps/rez/lib/python3.6/site-packages/rez/solver.py", line 1748, in get_graph
    and scope_r.conflicts_with(conflicting_request):
AttributeError: 'NoneType' object has no attribute 'conflicts_with'

I'm on an older version of rez (2.88.4) - has this been resolved in newer versions?
```

**Comment by maxnbk** [comment]
I agree, and this specific type of scenario is one that has produced a great deal of confusion that I have had to resolve with many colleagues over the years. I don't think that I consider the behavior a bug, as it's a clear result of a rather strict determinism and there are ways to address it by being more explicit in a rez request or in package definitions, but I do feel strongly that there is a solution that would remove confusion and make more explicit what is happening.

I specifically encounter the example of having a package that is varianted something like this:
```
variants = [
    [python-3.7],
    [python-3.7, maya-2050],
    [python-3.7, houdini-50],
]
```

The first variant is the "command line tool variant" that runs with a rezified python interpreter. The other two are built with their respective DCC-vendored interpreters. When asking for the package in a context without either of the other two, I would want the CLI one with a standard interpreter. But instead, I could get any of them. And I sure don't want to use maya's python interpreter when I don't need to. 

The solution to _my_ example is basically having "features" implemented completely, which would allow package definitions to be constructed with, say, a "cli" feature that can be requested, and is only present in the variant that I want to use via CLI.

In spite of not being completely intuitive at first, have you encountered any situation where having to be more explicit is causing an issue?

[...]

That stack trace sure looks like a bug though. :) I'm not sure if a newer rez fixes that issue, but if it's not difficult to update, it would be a very useful report. My intuition says probably, as I feel like I dealt with a similar issue that was eventually resolved, but I can't say for certain.

**Comment by JeanChristopheMorinPerso** [comment]
I have always considered this as a "bug". To me it's pretty non intuitive. We could make the solver a little bit more strict and limit itself to what matches (in this case C was requested by A, so pick that variant).

This has bitten soo many people. Yes "features" would help in some cases, but that's kind of the "expert" in the sense that features shouldn't be used to "fix" that behavior, but to do help the solver take decisions, which is kind of an advanced use case IMO.

That behavior is probably one of the features of rez that I dislike the most. I'd be worth having a discussion on what could be done to improve the experience of using variants, making them easier to use and understand, etc.

**Comment by maxnbk** [comment]
I think that even in the best-case scenario, you will still find people getting bitten unknowingly.

Let's pretend that the solver had a directive to "minimize the number of selected packages", in other words, not to pick the variant of anything that otherwise wasn't required.

Everything will be working just fine, until something that the user probably _expected_ to produce a conflict. But suddenly, an entire other alternate resolve via the excess variant is an option, and would be selected, potentially wildly changing behavior while not presenting the user with a clear conflict when they may have been expecting that original solve. The lack of a conflict might be just as difficult to troubleshoot. And a conflict is rez primary feedback mechanism to let you know that your solve is not a good state.

I think that if mutual exclusivity is to be expected, that it needs to be expressed. The question to me is, is there a better way to express that than we have currently via negations, because ultimately maintaining negations in variants becomes a problem of exponential permutations and unmaintainable the more variants are in the mix.

(To be clear, I am not arguing that we shouldn't perhaps do as above, ensure solves solve with a minimum of packages required, but simply expressing that attempting to constrain mutual exclusivity has other "intuitive faults" as well.)

**Comment by instinct-vfx** [comment]
There are many possible things you may want to add in such a scenario. From order of requests over preferring the latest version over fewer packages or the other way round. I would also like to add that more transparency would likely be helpful to make it clear to the user why certain packages were choosen by the solver. While the stacktrace is possibly still a bug is there a typo in the request (the single quote prior to the negation request)?

**Comment by dominiquekwiek** [comment]
@maxnbk

> That stack trace sure looks like a bug though. :) I'm not sure if a newer rez fixes that issue, but if it's not difficult to update, it would be a very useful report. My intuition says probably, as I feel like I dealt with a similar issue that was eventually resolved, but I can't say for certain.

Tried with Rez 2.111.4 and got a different error:

```
================================================================================
Building variant 1 (2/2)...
================================================================================
Resolving build environment: package_a package_d '!package_c'
resolve failed, by dkwiek@Dominiques-MacBook-Pro.local, on Fri Mar 10 16:26:34 2023, using Rez v2.111.2

requested packages:
package_a        
package_d        
!package_c       
~platform==osx   (implicit)
~arch==x86_64    (implicit)
~os==osx-13.0.1  (implicit)

The context failed to resolve:
The following package conflicts occurred: (package_c <--!--> !package_c)

Resolve paths starting from initial requests to conflict:
  package_a --> package_a-0.1.0 --> package_c
  !package_c --> package_c

To see a graph of the failed resolution, add --fail-graph in your rez-env or rez-build command.

The build environment could not be resolved:
The following package conflicts occurred: (package_c <--!--> !package_c)
```

So looks like the workaround you stated does not work.

**Comment by maxnbk** [comment]
Hmm. Yeah, apologies - I hadn't realized it would become impossible to solve for package_c, ever, even during build, with that definition...

**Comment by dominiquekwiek** [comment]
Okay, I have refined my use case and looks like the not requires (!) will solve my use case.  I redefine my use case as:

![Dependencies](https://user-images.githubusercontent.com/28793110/224494865-040eb07b-9fdc-4deb-a137-76e84654586b.png)

Defining the `package_b` package.py as:

```python
name = "package_b"

version = "0.1.0"

variants = [
    ["package_d"],
    ["!package_d"]
]

```

Now the resolve works as expected:

```
rez-env package_b package_a

resolved packages:
package_a-0.1.0  /dev/packages/package_a/0.1.0             (local)
package_b-0.1.0  /dev/packages/package_b/0.1.0/!package_d  (local)
package_c-0.1.0  /dev/packages/package_c/0.1.0             (local)
```

And:

```
rez-env package_b package_d

resolved packages:
package_b-0.1.0  /dev/packages/package_b/0.1.0/package_d  (local)
package_d-0.1.0  /dev/packages/package_d/0.1.0            (local)
package_e-0.1.0  /dev/packages/package_e/0.1.0            (local)
```

**Comment by JeanChristopheMorinPerso** [comment]
I found where the bug you reported was fixed: https://github.com/AcademySoftwareFoundation/rez/pull/1184
