### ISSUE TITLE
pip_install_remaps config in docs causes yaml parser error

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [AcademySoftwareFoundation/rez#1487]
I am trying to circumvent  https://github.com/AcademySoftwareFoundation/rez/issues/1481 by using `pip_install_remaps` configuration option. However, using the values from the [docs](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#pip_install_remaps) leads to a parsing error.

**Environment**
* windows-10.0.19045.SP0
* Rez version 2.112.0
* Rez python version Python 3.9.13

**To Reproduce**
1. Create a .rez_config file and copy the config from below
3. Open a shell and set the `REZ_CONFIG_FILE` environment variable to point to the file
4. run `rez-config`

<details>
<summary>.rez_config</summary>

```python
# Rez config file for Windows
{
    "pip_install_remaps": [
        # Typical bin copy behaviour
        # Path in record          | pip installed to    | copy to rez destination
        # ------------------------|---------------------|--------------------------
        # ../../bin/*             | bin/*               | bin/*
        {
            "record_path": r"^{p}{s}{p}{s}(bin{s}.*)",
            "pip_install": r"\1",
            "rez_install": r"\1",
        },
        # Fix for #821
        # Path in record          | pip installed to    | copy to rez destination
        # ------------------------|---------------------|--------------------------
        # ../../lib/python/*      | *                   | python/*
        {
            "record_path": r"^{p}{s}{p}{s}lib{s}python{s}(.*)",
            "pip_install": r"\1",
            "rez_install": r"python{s}\1",
        },
    ],
}
```
</details>

**Expected behavior**
The config should be successfully parsed

**Actual behavior**
<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\opt\rez\Scripts\rez\rez-config.exe\__main__.py", line 7, in <module>
  File "c:\opt\rez\lib\site-packages\rez\cli\_entry_points.py", line 112, in run_rez_config
    from rez.cli._main import run
  File "c:\opt\rez\lib\site-packages\rez\cli\_main.py", line 13, in <module>
    from rez.cli._util import subcommands, LazyArgumentParser, _env_var_true
  File "c:\opt\rez\lib\site-packages\rez\cli\_util.py", line 121, in <module>
    subcommands.update(load_plugin_cmd())
  File "c:\opt\rez\lib\site-packages\rez\cli\_util.py", line 94, in load_plugin_cmd
    for plugin_name in plugin_manager.get_plugins("command"):
  File "c:\opt\rez\lib\site-packages\rez\plugin_managers.py", line 360, in get_plugins
    return self._get_plugin_type(plugin_type).plugin_classes.keys()
  File "c:\opt\rez\lib\site-packages\rez\plugin_managers.py", line 338, in _get_plugin_type
    return self._plugin_types[plugin_type]()
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 308, in __call__
    self.instance = self.instance_class(*self.nargs, **self.kwargs)
  File "c:\opt\rez\lib\site-packages\rez\plugin_managers.py", line 103, in __init__
    self.load_plugins()
  File "c:\opt\rez\lib\site-packages\rez\plugin_managers.py", line 119, in load_plugins
    package = import_module(type_module_name)
  File "c:\opt\rez\lib\site-packages\rez\backport\importlib.py", line 36, in import_module
    __import__(name)
  File "c:\opt\rez\lib\site-packages\rezplugins\command\__init__.py", line 6, in <module>
    __path__ = extend_path(__path__, __name__)
  File "c:\opt\rez\lib\site-packages\rez\plugin_managers.py", line 72, in extend_path
    for dir_ in config.plugin_path:
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 664, in getter
    if key not in (self._data or {}):
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 698, in _data
    data = copy.deepcopy(self._data_without_overrides)
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 693, in _data_without_overrides
    data, self._sourced_filepaths = _load_config_from_filepaths(self.filepaths)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 964, in _load_config_from_filepaths
    data_ = loader(filepath_with_ext)
  File "c:\opt\rez\lib\site-packages\rez\backport\lru_cache.py", line 96, in wrapper
    result = user_function(*args, **kwds)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 936, in _load_config_yaml
    doc = yaml.load(content, Loader=yaml.FullLoader) or {}
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
rez.vendor.yaml.lib3.parser.ParserError: expected '<document start>', but found '{'
  in "<unicode string>", line 6, column 5:
        {
        ^
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\opt\rez\lib\site-packages\rez\util.py", line 148, in _atexit
    from rez.resolved_context import ResolvedContext
  File "c:\opt\rez\lib\site-packages\rez\resolved_context.py", line 8, in <module>
    from rez.package_repository import package_repository_manager
  File "c:\opt\rez\lib\site-packages\rez\package_repository.py", line 648, in <module>
    package_repository_manager = PackageRepositoryManager()
  File "c:\opt\rez\lib\site-packages\rez\package_repository.py", line 528, in __init__
    cache_size = config.resource_caching_maxsize
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 664, in getter
    if key not in (self._data or {}):
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 698, in _data
    data = copy.deepcopy(self._data_without_overrides)
  File "c:\opt\rez\lib\site-packages\rez\utils\data_utils.py", line 249, in __get__
    result = self.func(instance)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 693, in _data_without_overrides
    data, self._sourced_filepaths = _load_config_from_filepaths(self.filepaths)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 964, in _load_config_from_filepaths
    data_ = loader(filepath_with_ext)
  File "c:\opt\rez\lib\site-packages\rez\backport\lru_cache.py", line 96, in wrapper
    result = user_function(*args, **kwds)
  File "c:\opt\rez\lib\site-packages\rez\config.py", line 936, in _load_config_yaml
    doc = yaml.load(content, Loader=yaml.FullLoader) or {}
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\opt\rez\lib\site-packages\rez\vendor\yaml\lib3\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
rez.vendor.yaml.lib3.parser.ParserError: expected '<document start>', but found '{'
  in "<unicode string>", line 6, column 5:
        {
        ^
```
</details>

**Related Issues/PRs**
* #1481

**Comment by JeanChristopheMorinPerso** [comment]
You'll have to convert the example from python to YAML for it to work, or convert your config to python. There isn't much we can do about it. The docs could have both YAML and Python though.

**Comment by Anti-Distinctlyminty** [comment]
My config consists of a single python dict with keys that are the values I want to override. Even though I cannot find it documented anywhere that user config files should be of this form, it was the only way I could get it to work.
If my config uses the same form as in the docs, whereby a variable is assigned to, such as

```pytnon
pip_install_remaps = [
    # Typical bin copy behaviour
    # Path in record          | pip installed to    | copy to rez destination
    # ------------------------|---------------------|--------------------------
    # ../../bin/*             | bin/*               | bin/*
    {
        "record_path": r"^{p}{s}{p}{s}(bin{s}.*)",
        "pip_install": r"\1",
        "rez_install": r"\1",
    },
]
```

it does not work.

Any light you can shed on this would be welcome.

**Comment by Anti-Distinctlyminty** [comment]
I changed the name of my config file from `.rez_config` to `rez_config.py` and now the assignment of `pip_install_remaps` works.
Thank you @JeanChristopheMorinPerso
