### ISSUE TITLE
beginner help example_package / rez-build -i error 

### ISSUE THREAD

**Issue by veinfx** [AcademySoftwareFoundation/rez#1573]
im try rez-quickstart

PS C:\Users\worker\git\rez\example_packages\hello_world> rez-env python -- where python
c:\Users\worker\packages\python\3.8.3\platform-windows\arch-AMD64\os-windows-10.0.18362.SP0\bin\python
C:\Users\worker\AppData\Local\Programs\Python\Python38\python.exe

PS C:\Users\worker\git\rez\example_packages\hello_world> rez-build -i
Traceback (most recent call last):
  File "C:\Users\worker\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\worker\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\worker\rez\Scripts\rez\rez-build.exe\__main__.py", line 7, in <module>
  File "c:\users\worker\rez\lib\site-packages\rez\cli\_entry_points.py", line 106, in run_rez_build
    return run("build")
  File "c:\users\worker\rez\lib\site-packages\rez\cli\_main.py", line 191, in run
    returncode = run_cmd()
  File "c:\users\worker\rez\lib\site-packages\rez\cli\_main.py", line 183, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "c:\users\worker\rez\lib\site-packages\rez\cli\build.py", line 146, in command
    write_build_scripts=opts.scripts,
AttributeError: 'Namespace' object has no attribute 'scripts'

PS C:\Users\worker\git\rez\example_packages\hello_world> rez -V
Rez 2.112.0 from c:\users\worker\rez\lib\site-packages\rez (python 3.8)

**Comment by veinfx** [comment]
solved re install
