### ISSUE TITLE
Installing Rez with Python 3.12 causes errors becuase of old six vendored version

### ISSUE THREAD

**Issue by victorfleury** [AcademySoftwareFoundation/rez#1612]
I tried to install Rez on my machine with Python 3.12 on Fedora 39

The installation script seemed to run almost flawlessly except for the end where even if I got a `SUCCESS` message it turned out to be a faulty installation with the following traceback (see below)

After a bit of investigation from @JeanChristopheMorinPerso  it looks like the vendored `six` package is not enough up to date.
Rez bundles `six-1.12.0` when Python 3.12 comes up with `six-1.16.0`.

One solution would be to update the bundled version of `six` with Rez.
The other probably to remove the vendored version of `six` and use the one from the system Python already.

**Environment**
* OS : Fedora39
* Rez version : 2.113.0
* Rez python version : ? Running `rez-python --version` throws the error below.

**To Reproduce**
1. Run a linux distro with Python 3.12
2. Run the installation script

**Expected behavior**
The expected behaviour would have been to get Rez installed and ready to use.

**Actual behavior**
The actual result was this traceback : 
```
SUCCESS!
Rez executable installed to: /opt/rez/bin/rez/rez
Traceback (most recent call last):
  File "/opt/rez/bin/rez/rez", line 8, in <module>
    sys.exit(run_rez())
             ^^^^^^^^^
  File "/opt/rez/lib64/python3.12/site-packages/rez/cli/_entry_points.py", line 68, in run_rez
    from rez.cli._main import run
  File "/opt/rez/lib64/python3.12/site-packages/rez/cli/_main.py", line 13, in <module>
    from rez.cli._util import subcommands, LazyArgumentParser, _env_var_true
  File "/opt/rez/lib64/python3.12/site-packages/rez/cli/_util.py", line 123, in <module>
    subcommands.update(load_plugin_cmd())
                       ^^^^^^^^^^^^^^^^^
  File "/opt/rez/lib64/python3.12/site-packages/rez/cli/_util.py", line 90, in load_plugin_cmd
    from rez.config import config
  File "/opt/rez/lib64/python3.12/site-packages/rez/config.py", line 12, in <module>
    from rez.utils.scope import scoped_format
  File "/opt/rez/lib64/python3.12/site-packages/rez/utils/scope.py", line 8, in <module>
    from rez.vendor.six.six.moves import UserDict
ModuleNotFoundError: No module named 'rez.vendor.six.six.moves'

To activate Rez, add the following path to $PATH:
/opt/rez/bin/rez

You may also want to source the completion script (for bash):
source /opt/rez/completion/complete.sh
```

And running any `rez` commands would end up spitting out the same error message.

**Comment by JeanChristopheMorinPerso** [comment]
Thanks for reporting this! We'll have a couple of changes to do before we can support Python 3.12.

Hopefully we should be able to get to fixing this after support for Python 2.7 is removed (so post rez 3.0).

**Comment by victorfleury** [comment]
Looks like it is working fine with the new 3.0.0 version.
Just spotted a small typo in `rezconfig.py` making Python complain about a bad escaping sequence.

**Comment by JeanChristopheMorinPerso** [comment]
I think it'll fail later, somewhere in the plugin loading stage.

**Comment by victorfleury** [comment]
Indeed, trying both `rez bind` and `rez build` yields errors : 
```python
Traceback (most recent call last):
  File "/opt/rez/lib64/python3.12/site-packages/rez/plugin_managers.py", line 211, in get_plugin_class
    return self.plugin_classes[plugin_name]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'memory'
```

**Comment by anderslanglands** [comment]
I'm getting this too, on Ubuntu 24:
```bash
$ rez bind platform
/opt/rez/lib/python3.12/site-packages/rez/rezconfig.py:5: SyntaxWarning: invalid escape sequence '\ '
  """
searching /opt/rez/lib/python3.12/site-packages/rez/bind...
creating package 'platform' in /home/anders/packages...
16:39:43 ERROR    RezPluginError: Unrecognised package repository plugin: 'memory'
```
