### ISSUE TITLE
'use_variant_shortlinks' config entry ignore by rez-cp

### ISSUE THREAD

**Issue by garrett-wbpa** [AcademySoftwareFoundation/rez#1701]
Hello,

I've disabled variant shortlinks for my windows machine using a rez config json file. I went to rez-cp a package to my repository and noticed that rez-cp was still trying to create a _v shortlink folder. It fails due to permissions, but rez-cp continues on and copies the full variant folder anwyay.

**Environment**
* OS Windows
* Rez version 3.0.0
* Rez python version 3.9.13

**To Reproduce**
1. set 'use_variant_shortlinks=false' in a rez config file
2. rez-cp a package into a repository and see that a shortlink folder is still created.

**Expected behavior**
I expect rez-cp to skip the shortlink creation when the config specifies to do so.

**Actual behavior**
A _v folder is created even though my config is disabling them.

**Comment by JeanChristopheMorinPerso** [comment]
>I've disabled variant shortlinks for my windows machine using a rez config json file

We don't support JSON config files. Is it a typo?

**Comment by JeanChristopheMorinPerso** [comment]
Just to be sure that your config is loaded properly, would you mind giving me the result of `rez-config use_variant_shortlinks` please?

**Comment by garrett-wbpa** [comment]
Good point. I've just now confirmed that `rez-config use_variant_shortlinks` returns `False` and re-run my repro steps with the same issue. Oddly, I get a string formatting error when trying to copy a package containing the symlinked short variants, but no issue when copying something simple like `os`.

```
REZ_CONFIG_FILE=/w/CREW/garrett.broussard/scripts/rez_config/rez_config_002.yaml rez-config use_variant_shortlinks
False
REZ_CONFIG_FILE=/w/CREW/garrett.broussard/scripts/rez_config/rez_config_002.yaml rez-cp --dest-path ~/wbpa/tmp/wbpa_001 --allow-empty pycue
Traceback (most recent call last):
  File "C:\Users\garrett\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\garrett\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\opt\rez\Scripts\rez\rez-cp.exe\__main__.py", line 7, in <module>
  File "c:\opt\rez\lib\site-packages\rez\cli\_entry_points.py", line 127, in run_rez_cp
    return run("cp")
  File "c:\opt\rez\lib\site-packages\rez\cli\_main.py", line 191, in run
    returncode = run_cmd()
  File "c:\opt\rez\lib\site-packages\rez\cli\_main.py", line 183, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "c:\opt\rez\lib\site-packages\rez\cli\cp.py", line 156, in command
    result = copy_package(
  File "c:\opt\rez\lib\site-packages\rez\package_copy.py", line 202, in copy_package
    _copy_variant_payload(
  File "c:\opt\rez\lib\site-packages\rez\package_copy.py", line 249, in _copy_variant_payload
    "Cannot copy source variant %s - its root does not appear to "
TypeError: not enough arguments for format string
```

**Comment by JeanChristopheMorinPerso** [comment]
Umm, that's an error in our code.

https://github.com/AcademySoftwareFoundation/rez/blob/a13f7bb362cbb05e73f88e9f771c36005c1e9f4a/src/rez/package_copy.py#L244-L247

If should be:
```python
        raise PackageCopyError(
            "Cannot copy source variant %s - its root does not appear to "
            "be present on disk (%s)." % (src_variant.uri, variant_root)
        )
```
