### ISSUE TITLE
rez depends -p crashes

### ISSUE THREAD

**Issue by czerouni** [AcademySoftwareFoundation/rez#1887]
Describe the bug here.

**Environment**
* OS - rocky9
* Rez version - 3.0.0, 3.1.1, 3.2.1
* Rez python version - 3.9.16

**To Reproduce**
$ rez depends -p boost
where boost is a Rez package installed to the network

**Expected behavior**
Looking for rez dependencies

**Actual behavior**
```
$ rez depends --private-build-requires boost

Searching [#################               ] 188/342Traceback (most recent call last):
  File "/laika/dist/third_party/linux_rocky9_x86_64/rez/RELEASE/bin/rez/rez", line 8, in <module>
    sys.exit(run_rez())
  File "/net/ent-prod.nfs.laika.com/ifs/laika/dist/third_party/linux_rocky9_x86_64/rez/v3.1.1/lib/python3.9/site-packages/rez/cli/_entry_points.py", line 69, in run_rez
    return run()
  File "/net/ent-prod.nfs.laika.com/ifs/laika/dist/third_party/linux_rocky9_x86_64/rez/v3.1.1/lib/python3.9/site-packages/rez/cli/_main.py", line 189, in run
    returncode = run_cmd()
  File "/net/ent-prod.nfs.laika.com/ifs/laika/dist/third_party/linux_rocky9_x86_64/rez/v3.1.1/lib/python3.9/site-packages/rez/cli/_main.py", line 181, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "/net/ent-prod.nfs.laika.com/ifs/laika/dist/third_party/linux_rocky9_x86_64/rez/v3.1.1/lib/python3.9/site-packages/rez/cli/depends.py", line 61, in command
    pkgs_list, g = get_reverse_dependency_tree(
  File "/net/ent-prod.nfs.laika.com/ifs/laika/dist/third_party/linux_rocky9_x86_64/rez/v3.1.1/lib/python3.9/site-packages/rez/package_search.py", line 90, in get_reverse_dependency_tree
    if not req.conflict:
AttributeError: 'str' object has no attribute 'conflict'
```

**Regression**
I tried this with 3 versions of rez, with the same result. For reference, we have compiled `boost` with RPATH embeds, we are not setting LD_LIBRARY_PATH in the `package.py` file.

**Comment by czerouni** [comment]
This came from a developer at the studio. Let me see if I can reproduce this. Also, we have moved away from using RPATH, so maybe this problem went away as well - not sure if they are related though.

**Comment by JeanChristopheMorinPerso** [comment]
rez depends doesn't load/execute packages. It just goes through the package repositories and tries to find everything.
