### ISSUE TITLE
Stack Trace when building with two make systems available

### ISSUE THREAD

**Issue by maxnbk** [AcademySoftwareFoundation/rez#292]
[On Windows using msys shell]
$ rez-build -b cmake
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\maxnbk\Desktop\Projects\Method\packages\rez\2.0.rc1.36\Scripts\rez\rez-build.exe__main__.py", line 2, in <module>
  File "c:\users\maxnbk\desktop\projects\method\packages\rez\2.0.rc1.36\lib\site-packages\rez-2.0.rc1.36-py2.7.egg\rez\cli_main.py", line 117, in run
    returncode = run_cmd()
  File "c:\users\maxnbk\desktop\projects\method\packages\rez\2.0.rc1.36\lib\site-packages\rez-2.0.rc1.36-py2.7.egg\rez\cli_main.py", line 109, in run_cmd
    return opts.func(opts, opts.parser, arg_groups[1:])
  File "c:\users\maxnbk\desktop\projects\method\packages\rez\2.0.rc1.36\lib\site-packages\rez-2.0.rc1.36-py2.7.egg\rez\cli\build.py", line 100, in command
    child_build_args=child_build_args)
  File "c:\users\maxnbk\desktop\projects\method\packages\rez\2.0.rc1.36\lib\site-packages\rez-2.0.rc1.36-py2.7.egg\rez\build_system.py", line 52, in create_build_system
    child_build_args=child_build_args)
  File "c:\users\maxnbk\desktop\projects\method\packages\rez\2.0.rc1.36\lib\site-packages\rez-2.0.rc1.36-py2.7.egg\rezplugins\build_system\cmake.py", line 90, in **init**
    self.build_target = (opts and opts.build_target) or \
AttributeError: 'Namespace' object has no attribute 'build_target'

**Comment by JeanChristopheMorinPerso** [comment]
I'm guessing this has been fixed by now.
