### ISSUE TITLE
stack trace when running rez-build -s -i with build_command set

### ISSUE THREAD

**Issue by maxnbk** [AcademySoftwareFoundation/rez#430]
running: rez-build -s -i --variants 0
package.py has: build_command = "python {root}/rezbuild.py {install}"
output:
```
--------------------------------------------------------------------------------
Building package-major.minor...
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Building variant 1/3...
--------------------------------------------------------------------------------

Resolving build environment: [build-env]
(resolve info)

Invoking custom build system...
Traceback (most recent call last):
  File "/path/to/rez/2.13.0/payload/bin/rez/rez-build", line 4, in <module>
    run('build')
  File "/path/to/rez/2.13.0/payload/local/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rez/cli/_main.py", line 118, in run
    returncode = run_cmd()
  File "/path/to/rez/2.13.0/payload/local/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rez/cli/_main.py", line 110, in run_cmd
    return opts.func(opts, opts.parser, arg_groups[1:])
  File "/path/to/rez/2.13.0/payload/local/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rez/cli/build.py", line 128, in command
    variants=opts.variants)
  File "/path/to/rez/2.13.0/payload/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rezplugins/build_process/local.py", line 36, in build
    install=install)
  File "/path/to/rez/2.13.0/payload/local/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rez/build_process_.py", line 184, in visit_variants
    result = func(variant, **kwargs)
  File "/path/to/rez/2.13.0/payload/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rezplugins/build_process/local.py", line 193, in _build_variant
    install=install)
  File "/path/to/rez/2.13.0/payload/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rezplugins/build_process/local.py", line 144, in _build_variant_base
    build_type=build_type)
  File "/path/to/rez/2.13.0/payload/lib/python2.7/site-packages/rez-2.13.0-py2.7.egg/rezplugins/build_system/custom.py", line 92, in build
    create_forwarding_script(build_env_script,
NameError: global name 'create_forwarding_script' is not defined```

**Comment by JeanChristopheMorinPerso** [comment]
Fixed in https://github.com/AcademySoftwareFoundation/rez/pull/968
