### ISSUE TITLE
Ubuntu: `rez selftest` tests failing due to default shell resolving to tcsh

### ISSUE THREAD

**Issue by uncojohnco** [AcademySoftwareFoundation/rez#584]
Thought I would test REZ on my personal machine. After installing rez and running `rez self`, 12 tests fail from:
- rez.tests.test_build.TestBuild
- rez.tests.test_release.TestRelease
- rez.tests.test_shells.TestShells

[rez-selftest errors.log](https://github.com/nerdvegas/rez/files/2986027/rez-selftest.errors.log)

I have the **bash** shell installed as per Ubuntu and haven't configured REZ at all, though it seems to be resolving the default shell as **tcsh** :frowning: 

```python
$ rez-python
>>> from rez.config import config
>>> config.default_shell
`tcsh`
```
Example Traceback
```
Traceback (most recent call last):
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/util.py", line 176, in wrapper
    func(self, *args, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/util.py", line 187, in _fn
    fn(self, *args, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/test_build.py", line 135, in test_build_whack
    self.assertRaises(BuildError, builder.build, clean=True)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/vendor/unittest2/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rezplugins/build_process/local.py", line 37, in build
    install=install)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/build_process_.py", line 197, in visit_variants
    result = func(variant, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rezplugins/build_process/local.py", line 227, in _build_variant
    install=install)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rezplugins/build_process/local.py", line 167, in _build_variant_base
    build_type=build_type)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rezplugins/build_system/bez.py", line 97, in build
    actions_callback=callback)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/resolved_context.py", line 871, in _check
    return fn(self, *nargs, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/resolved_context.py", line 1238, in execute_shell
    executor = self._create_executor(sh, parent_environ)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/resolved_context.py", line 1554, in _create_executor
    parent_variables=parent_vars)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/rex.py", line 1087, in __init__
    self.manager.shebang()
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/rex.py", line 415, in shebang
    self.interpreter.shebang()
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/shells.py", line 397, in shebang
    self._addline("#!%s" % self.executable)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rezplugins/shell/tcsh.py", line 19, in executable
    cls._executable = Shell.find_executable('tcsh')
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/shells.py", line 124, in find_executable
    raise RuntimeError("Couldn't find executable '%s'." % name)
RuntimeError: Couldn't find executable 'tcsh'.

```

---

**- Rez version:** 
  - 2.28.0

**- Platform and operating system you were using:**
```bash
johno-dev@johnodev-VirtualBox:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
johno-dev@johnodev-VirtualBox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
johno-dev@johnodev-VirtualBox:~$ hostnamectl
   Static hostname: johnodev-VirtualBox
         Icon name: computer-vm
           Chassis: vm
        Machine ID: caf4827aa85442238fa3060310e82c9f
           Boot ID: bd714a0133834208998ee80260928e88
    Virtualization: oracle
  Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.18.0-16-generic
      Architecture: x86-64
johno-dev@johnodev-VirtualBox:~$  uname -r
4.18.0-16-generic
```
**- Contextual information (what were you trying to do using Rez);**
Validate rez build/install via selftest

**- Simplest possible steps to reproduce.**
  - `python2 install.py -v "$HOME/rez"`
  - `rez selftest`

**Comment by uncojohnco** [comment]
Had a look at this again tonight and the `default_shell` value returns an empty string :confused: 
```shell
$ rez-python
>>> from rez.config import config
>>> config.default_shell
``
```
---

`sudo apt install tcsh` allows the selftest to succed further, though **test_rex_code_alias** fails with the bellow traceback:

```python
======================================================================
FAIL: test_rex_code_alias (rez.tests.test_shells.TestShells)
Ensure PATH changes do not influence the alias command.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/util.py", line 176, in wrapper
    func(self, *args, **kwargs)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/test_shells.py", line 327, in test_rex_code_alias
    _execute_code(_alias_after_path_manipulation)
  File "/home/johno-dev/rez/rez-2.28.0/lib/python2.7/site-packages/rez-2.28.0-py2.7.egg/rez/tests/test_shells.py", line 312, in _execute_code
    self.assertEqual(p.returncode, 0)
AssertionError: 2 != 0

-----------------------------------------------------n't -----------------
Ran 124 tests in 73.247s

FAILED (failures=1)
```
<kbd>
Note: This isn't stopping me from tinkering with rez in my environ, but just flaging this odd anomolly :man_shrugging: 
</kbd>

**Comment by nerdvegas** [comment]
Hmm yeah I do believe there is a tcsh bug or two. As to why it's defaulting
to tcsh, I'm not sure..

**Comment by bfloch** [comment]
Can you try again with the latest release on a fresh install?
