### ISSUE TITLE
Import pip error when installing OpenTImelineIO==0.11.0 with rez pip

### ISSUE THREAD

**Issue by spsalefeve** [AcademySoftwareFoundation/rez#900]
I get the following error when trying to install OpenTImelineIO 0.11.0 with rez-pip:

```bash
rez pip -i  OpenTimelineIO==0.11.0
08:59:13 INFO     Trying to use pip from python package
08:59:14 INFO     Found pip-20.1.1 inside /app/package/int/python/3.7-sps.1.1/package.py. Will use it with /usr/local/bin/python3
08:59:14 INFO     Installing 'OpenTimelineIO==0.11.0' with pip taken from '/usr/local/bin/python3'
Collecting OpenTimelineIO==0.11.0
  Using cached https://files.pythonhosted.org/packages/51/43/c0340807670aab3ead9c5f90f59597f34f9f936a67120e6e57a2c80ea8c9/OpenTimelineIO-0.11.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/local/bin/python3 /home/alefeve/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /data/alefeve/tmp/tmprcg3_g1g:
  Traceback (most recent call last):
    File "/home/alefeve/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/alefeve/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/alefeve/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/data/alefeve/tmp/pip-build-env-z7n9s86w/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/data/alefeve/tmp/pip-build-env-z7n9s86w/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/data/alefeve/tmp/pip-build-env-z7n9s86w/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 249, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/data/alefeve/tmp/pip-build-env-z7n9s86w/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 34, in <module>
      import pip
  ModuleNotFoundError: No module named 'pip'
  
  ----------------------------------------
Command "/usr/local/bin/python3 /home/alefeve/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /data/alefeve/tmp/tmprcg3_g1g" failed with error code 1 in /data/alefeve/tmp/pip-install-_tu6rem3/OpenTimelineIO
```
This was tested with rez 2.59.1 and 2.60.1, with python-2.7 and python-3.7.
The latest version of OpenTimelineIO (0.12.1) can be installed with rez pip without any problem.

**Comment by JeanChristopheMorinPerso** [comment]
These problems should theorically be fixed with newer OTIO releases.
