### ISSUE TITLE
rez-pip crashes with `TypeError`

### ISSUE THREAD

**Issue by kguyaux** [AcademySoftwareFoundation/rez#949]
platform=linux
arch=x86_64
os=LinuxMint-19.1

```
$ rez pip --python 3.7 --install PyQt5
12:32:59 INFO     Trying to use pip from python package
Traceback (most recent call last):
  File "/opt/rez/bin/rez/rez", line 8, in <module>
    sys.exit(run_rez())
  File "/opt/rez/lib/python3.7/site-packages/rez/cli/_entry_points.py", line 64, in run_rez
    return run()

  File "/opt/rez/lib/python3.7/site-packages/rez/cli/_main.py", line 170, in run
    returncode = run_cmd()
  File "/opt/rez/lib/python3.7/site-packages/rez/cli/_main.py", line 162, in run_cmd
    return func(opts, opts.parser, extra_arg_groups)
  File "/opt/rez/lib/python3.7/site-packages/rez/cli/pip.py", line 76, in command
    extra_args=opts.extra)
  File "/opt/rez/lib/python3.7/site-packages/rez/pip.py", line 261, in pip_install_package
    py_exe, context = find_pip(pip_version, python_version)
  File "/opt/rez/lib/python3.7/site-packages/rez/pip.py", line 95, in find_pip
    python_version, pip_version=version
  File "/opt/rez/lib/python3.7/site-packages/rez/pip.py", line 203, in find_pip_from_context
    py_exe = find_python_in_context(context)
  File "/opt/rez/lib/python3.7/site-packages/rez/pip.py", line 142, in find_python_in_context
    python_package = context.get_resolved_package("python")
  File "/opt/rez/lib/python3.7/site-packages/rez/resolved_context.py", line 419, in get_resolved_package
    pkgs = [x for x in self._resolved_packages if x.name == name]
TypeError: 'NoneType' object is not iterable
```

**Comment by alexey-pelykh** [comment]
Related to #1325
